[package]
name = "proyecto_robotica"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
ndarray = "0.15"
csv = "1.1"
plotters = "0.3"
itertools = "0.10"
macroquad = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
